services:
  - type: web
    name: study-buddy-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        sync: false
      - key: MONGO_DB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: NODE_VERSION
        value: 20.9.0
